In [5]:
# numerical python (numpy) - numpy is one of python's core libraries used for scientific computing.
# for this module, it focusews more on numpy's objects and tools for manipulating arrays
# arrays - a data set that stores multiple items of the same data type under one name.

import numpy as np # this imports the library in the notebook

# ndarray: a multi-dimebnsional container of items of the same data type and size
# The number of dimensions and items in an array is defined by its shape, 
# which is a tuple of N non-negative integers that specify the sizes of each dimension.

1d, 2d, and 3d arrays: 


(2, 3)

In [12]:
print ("numpy demo 1: creating and inspeacting ndarrays")

# i will showcase 3 different arrays: vectors(1D), matrices(2D), and tensors(2D)

# in this demo, we will be focusing on two functions: np.array and .shape
# example: 

vec = np.array([1,2,3]) # initializes an array
vec
#vec.shape  # shows the number of items of in an array (remove hashtag and this comment to show shape)


numpy demo 1: creating and inspeacting ndarrays


(3,)

In [11]:
print("for matrices, the .shape function shows the  number of rows and columns")
mat = np.array([(1,2,3),(4,5,6)])
mat
#mat.shape (remove hashtag and this comment to show shape)

for matrices, the .shape function shows the  number of rows and columns


(2, 3)

In [18]:
print("for tensors, the .shape function shows the  number of rows, columns, and layers of the array.")
ten = np.array([[(1,2,3,),(5,6,7)],[(8,9,10),(11,12,13)]])
ten
#ten.shape (remove hashtag and this comment to show shape)

for tensors, the .shape function shows the  number of rows, columns, and layers of the array.


array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[ 8,  9, 10],
        [11, 12, 13]]])

In [ ]:
print ("logical and arithmetic operators on arrays")

# i will be making 3 arrays and perform arithmetic and logical operations on those 3 on seperate cells

In [25]:
a = np.array([(2,4,6),(8,10,12)])
a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [24]:
b = np.array([(4,9),(16,25),(36,49)])
b

array([[ 4,  9],
       [16, 25],
       [36, 49]])

In [23]:
c = np.array([2,3,5])
c

array([2, 3, 5])

In [26]:
c-a

array([[ 0, -1, -1],
       [-6, -7, -7]])

In [27]:
a+c

array([[ 4,  7, 11],
       [10, 13, 17]])

In [28]:
a*c

array([[ 4, 12, 30],
       [16, 30, 60]])

In [29]:
c*a

array([[ 4, 12, 30],
       [16, 30, 60]])

In [30]:
a/c

array([[1.        , 1.33333333, 1.2       ],
       [4.        , 3.33333333, 2.4       ]])

In [31]:
c/a

array([[1.        , 0.75      , 0.83333333],
       [0.25      , 0.3       , 0.41666667]])

In [36]:
print("we got more math shi omfggg")

b

we got more math shi omfggg


array([[ 4,  9],
       [16, 25],
       [36, 49]])

In [37]:
np.exp(b)

array([[5.45981500e+01, 8.10308393e+03],
       [8.88611052e+06, 7.20048993e+10],
       [4.31123155e+15, 1.90734657e+21]])

In [38]:
np.sqrt(b)

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [39]:
np.sin(b)

array([[-0.7568025 ,  0.41211849],
       [-0.28790332, -0.13235175],
       [-0.99177885, -0.95375265]])

In [40]:
np.log(b)

array([[1.38629436, 2.19722458],
       [2.77258872, 3.21887582],
       [3.58351894, 3.8918203 ]])

In [ ]:
# yung logical operators ng arrays tuloy nyo nalang sa learning matireals canvas huhu i cant do this anymore